"""

Revision ID: 2af9809dd2da
Revises: 624c16225c7f
Create Date: 2022-10-14 03:39:15.640350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2af9809dd2da'
down_revision = '624c16225c7f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scrum_scrumday', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ignored', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scrum_scrumday', schema=None) as batch_op:
        batch_op.drop_column('ignored')

    # ### end Alembic commands ###
