"""

Revision ID: 624c16225c7f
Revises: 
Create Date: 2022-10-14 02:55:28.669091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '624c16225c7f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scrum_scrumservers',
    sa.Column('guild', sa.BigInteger(), nullable=False),
    sa.Column('channel', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('guild')
    )
    op.create_table('scrum_scrumday',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('guild', sa.BigInteger(), nullable=True),
    sa.Column('post_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['guild'], ['scrum_scrumservers.guild'], name='fk_scrum_scrumday_scrum_scrumservers_guild_guild'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scrum_scrumentry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.Column('user', sa.BigInteger(), nullable=False),
    sa.Column('previous', sa.Text(), nullable=False),
    sa.Column('next', sa.Text(), nullable=False),
    sa.Column('blockers', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['day'], ['scrum_scrumday.id'], name='fk_scrum_scrumentry_scrum_scrumday_id_day'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scrum_scrumentry')
    op.drop_table('scrum_scrumday')
    op.drop_table('scrum_scrumservers')
    # ### end Alembic commands ###
