"""

Revision ID: 0cfbbff1a1e0
Revises: 
Create Date: 2022-07-30 01:47:41.220095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cfbbff1a1e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('namecolor.namecolorroless',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.BigInteger(), nullable=False),
    sa.Column('color', sa.String(length=6), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('namecolor.namecolorroless')
    # ### end Alembic commands ###
